# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c5NEJC_4uxFxYGa70aAaXIAZR-YWwOXr
"""

# CUSTOMER DATA - COMPLETE ML PREPROCESSING


import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split


# 1. Create Customer Dataset


data = {
    "Age": [20, 25, 30, 35, 40, 28, 45, 32, 23, 38],
    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],
    "City": [
        "Delhi", "Mumbai", "Delhi", "Chandigarh", "Mumbai",
        "Delhi", "Chandigarh", "Mumbai", "Delhi", "Chandigarh"
    ],
    "Salary": [
        25000, 35000, 50000, 65000, 75000,
        42000, 90000, 55000, 30000, 70000
    ],
    "Experience": [
        1, 3, 6, 10, 12,
        4, 15, 7, 2, 11
    ],
    "Purchased": [
        0, 0, 1, 1, 1,
        0, 1, 1, 0, 1
    ]
}

df = pd.DataFrame(data)

print("========== ORIGINAL DATA ==========")
print(df)
print("\nOriginal Shape:", df.shape)



# 2. Identify X and y


X = df.drop("Purchased", axis=1)
y = df["Purchased"]

print("\n========== X FEATURES ==========")
print(X)

print("\n========== y TARGET ==========")
print(y)


# 3. Encode Gender using Label Encoding

encoder = LabelEncoder()

X["Gender"] = encoder.fit_transform(X["Gender"])

print("\n========== AFTER LABEL ENCODING ==========")
print(X)



# 4. One-Hot Encoding for City


X = pd.get_dummies(X, columns=["City"], dtype=int)

print("\n========== AFTER ONE-HOT ENCODING ==========")
print(X)



# 5. Train/Test Split


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\n========== TRAIN/TEST SPLIT ==========")

print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape :", y_test.shape)



# 6. Feature Scaling


scaler = StandardScaler()

# IMPORTANT:
# Fit scaler only on training data
X_train_scaled = scaler.fit_transform(X_train)

# Transform test data using the same scaler
X_test_scaled = scaler.transform(X_test)



# 7. Convert Scaled Data to DataFrame


X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns,
    index=X_train.index
)

X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns,
    index=X_test.index
)

# 8. Print Final Results


print("\n========== SCALED TRAIN DATA ==========")
print(X_train_scaled)

print("\n========== SCALED TEST DATA ==========")
print(X_test_scaled)



# 9. Final Shapes


print("\n========== FINAL SHAPES ==========")

print("Original Data:", df.shape)
print("X:", X.shape)
print("y:", y.shape)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

print("X_train_scaled:", X_train_scaled.shape)
print("X_test_scaled :", X_test_scaled.shape)