# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XHwpi-HDFLau6cY9RlQHkYWiylIPVaUr
"""

import pandas as pd
df=pd.read_csv("/content/housing.csv")
print(df.head(2))
print(df.shape)
print(df.info())
print(df.describe())

##Explore:
print(df["total_rooms"].unique())
print(df["longitude"].value_counts())

##Filtering
print(df[df["housing_median_age"]>80])
print(df[df["total_rooms"]>400])
print(df[(df["total_rooms"]>80)&(df["median_income"]<23)])

##Sorting
print(df.sort_values("total_rooms",ascending=False))
print(df.sort_values("median_income",ascending=False).head(3))

##groupby()
print(df.groupby("total_rooms")["median_income"].mean())
print(df.groupby("longitude")["latitude"].mean())
print(df.groupby("housing_median_age")["ocean_proximity"].max())

