# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AXeIZqr7WywaPcUx1UMMUppvD1-59FuX
"""

### Pandas library
import pandas as pd
##Series
marks=pd.Series([85,90,78,92,88])
print(marks)
print(marks[0])
print(marks.mean())
print(marks.head())
print(marks.tail())

###DataFrame
data={'Name':['Rahul','Ansh','Riya','Aman'],'Age':[21,22,20,23],'Marks':[85,92,78,88]}
df=pd.DataFrame(data)
print(df)
##Explore
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print(df.index)
print(df.dtypes)
print(df.describe())

##Select Columns
print(df['Name'])
print(df['Marks'])
print(df[['Name','Marks']])

##Select Rows
print(df.iloc[0])
print(df.iloc[1:3])

#Add Columns
df['Passed']=df['Marks']>=40
df['Bonus']=5
df['Final_Marks']=df['Marks']+df['Bonus']
print(df)
#Analysis
print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].min())
print(df['Marks'].sum())
print(df['Marks'].median())
#Filtering
print(df[df['Marks']>80])
print(df[df['Age']>21])
print(df[(df['Marks']>80)&(df['Age']>20)])

#python
import pandas as pd

# Create DataFrame
data = {
    'Name': ['Aman', 'Riya', 'Rahul', 'Simran', 'Karan'],
    'Age': [20, 22, 21, 23, 20],
    'Marks': [75, 92, 68, 88, 95],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Chandigarh', 'Delhi']
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)


# 1. Find students with marks > 80
print("\nStudents with marks > 80:")
print(df[df['Marks'] > 80])


# 2. Find students from Delhi
print("\nStudents from Delhi:")
print(df[df['City'] == 'Delhi'])


# 3. Find average, highest and lowest marks
print("\nAverage Marks:", df['Marks'].mean())
print("Highest Marks:", df['Marks'].max())
print("Lowest Marks:", df['Marks'].min())


# 4. Find students older than 21
print("\nStudents older than 21:")
print(df[df['Age'] > 21])


# 5. Add Passed column
df['Passed'] = df['Marks'] >= 40

print("\nDataFrame with Passed column:")
print(df)


# 6. Add 5 bonus marks
df['Marks'] = df['Marks'] + 5

print("\nMarks after adding 5 bonus marks:")
print(df)


# 7. Display Name and Marks
print("\nName and Marks:")
print(df[['Name', 'Marks']])


# 8. Display first 3 students
print("\nFirst 3 students:")
print(df.head(3))


### Homework: Employee DataFrame

##python
import pandas as pd

# Create employee DataFrame
data = {
    'Name': [
        'Aman', 'Riya', 'Rahul', 'Simran', 'Karan',
        'Neha', 'Arjun', 'Priya', 'Vikas', 'Anjali'
    ],
    'Age': [25, 28, 30, 26, 32, 29, 35, 27, 31, 24],
    'Department': [
        'IT', 'HR', 'Finance', 'IT', 'Sales',
        'HR', 'Finance', 'Sales', 'IT', 'HR'
    ],
    'Salary': [
        45000, 52000, 60000, 48000, 75000,
        55000, 80000, 50000, 65000, 42000
    ]
}

employees = pd.DataFrame(data)

print("Employee DataFrame:")
print(employees)


# Average salary
average_salary = employees['Salary'].mean()
print("\nAverage Salary:", average_salary)


# Highest salary
highest_salary = employees['Salary'].max()
print("Highest Salary:", highest_salary)


# Employees earning above average salary
above_average = employees[employees['Salary'] > average_salary]

print("\nEmployees above average salary:")
print(above_average)



