# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18zaDdpCx6Y88_GHM_DBORO3GPTNQd5MV
"""

## Introduction to machine learning
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

data = {
"Hours_Studied": [1, 2, 3, 4, 5, 6, 7, 8],
"Marks": [35, 42, 50, 58, 60, 64, 83, 90]
}
df = pd.DataFrame(data)

# STEP 1 Featured and target
X = df[["Hours_Studied"]]
y = df["Marks"]
print(X)
print(y)
## X contains input features. y contains the target we want to predict.

##Step 2: Train/Test Split

X_train, X_test, y_train, y_test = train_test_split(
X, y,
test_size=0.25,
random_state=42
)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

###STEP3: Create and Train the Model

model = LinearRegression()
model.fit(X_train, y_train)

###STEP4: Make Predictions

y_pred = model.predict(X_test)
print(y_pred)

##7. Predict New Data
new_data = pd.DataFrame({
"Hours_Studied": [5.5]
})
prediction = model.predict(new_data)
print("Predicted Marks:", prediction[0])

