# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14t2MPsbUlk_ocWI9DwYRTSlsdDVY3uiT
"""

##operators in python
# ============================================
#        PYTHON OPERATORS - COMPLETE PROGRAM
# ============================================

a = 10
b = 3

print("========== PYTHON OPERATORS ==========\n")

# ------------------------------------------------
# 1. ARITHMETIC OPERATORS
# ------------------------------------------------
print("1. ARITHMETIC OPERATORS")

print("a + b  =", a + b)    # Addition
print("a - b  =", a - b)    # Subtraction
print("a * b  =", a * b)    # Multiplication
print("a / b  =", a / b)    # Division
print("a // b =", a // b)   # Floor Division
print("a % b  =", a % b)    # Modulus
print("a ** b =", a ** b)   # Exponentiation


# ------------------------------------------------
# 2. COMPARISON OPERATORS
# ------------------------------------------------
print("\n2. COMPARISON OPERATORS")

print("a == b :", a == b)   # Equal
print("a != b :", a != b)   # Not Equal
print("a > b  :", a > b)    # Greater Than
print("a < b  :", a < b)    # Less Than
print("a >= b :", a >= b)   # Greater Than or Equal
print("a <= b :", a <= b)   # Less Than or Equal


# ------------------------------------------------
# 3. LOGICAL OPERATORS
# ------------------------------------------------
print("\n3. LOGICAL OPERATORS")

x = True
y = False

print("x and y :", x and y)
print("x or y  :", x or y)
print("not x   :", not x)


# ------------------------------------------------
# 4. ASSIGNMENT OPERATORS
# ------------------------------------------------
print("\n4. ASSIGNMENT OPERATORS")

num = 10
print("Initial value:", num)

num += 5
print("num += 5  :", num)

num -= 3
print("num -= 3  :", num)

num *= 2
print("num *= 2  :", num)

num /= 4
print("num /= 4  :", num)

num //= 2
print("num //= 2 :", num)

num %= 3
print("num %= 3  :", num)

num **= 2
print("num **= 2 :", num)


# ------------------------------------------------
# 5. BITWISE OPERATORS
# ------------------------------------------------
print("\n5. BITWISE OPERATORS")

p = 10
q = 4

print("p & q  =", p & q)     # AND
print("p | q  =", p | q)     # OR
print("p ^ q  =", p ^ q)     # XOR
print("~p     =", ~p)        # NOT
print("p << 1  =", p << 1)   # Left Shift
print("p >> 1  =", p >> 1)   # Right Shift


# ------------------------------------------------
# 6. MEMBERSHIP OPERATORS
# ------------------------------------------------
print("\n6. MEMBERSHIP OPERATORS")

fruits = ["apple", "banana", "mango", "orange"]

print("'apple' in fruits     :", "apple" in fruits)
print("'grapes' in fruits    :", "grapes" in fruits)
print("'grapes' not in fruits:", "grapes" not in fruits)


# ------------------------------------------------
# 7. IDENTITY OPERATORS
# ------------------------------------------------
print("\n7. IDENTITY OPERATORS")

list1 = [1, 2, 3]
list2 = list1
list3 = [1, 2, 3]

print("list1 is list2     :", list1 is list2)
print("list1 is list3     :", list1 is list3)
print("list1 is not list3 :", list1 is not list3)


# ------------------------------------------------
# 8. UNARY OPERATORS
# ------------------------------------------------
print("\n8. UNARY OPERATORS")

n = 10

print("+n =", +n)
print("-n =", -n)
print("not True =", not True)


# ------------------------------------------------
# 9. OPERATOR PRECEDENCE
# ------------------------------------------------
print("\n9. OPERATOR PRECEDENCE")

result = 10 + 5 * 2
print("10 + 5 * 2 =", result)

result = (10 + 5) * 2
print("(10 + 5) * 2 =", result)


# ------------------------------------------------
# 10. PRACTICAL EXAMPLE
# ------------------------------------------------
print("\n10. PRACTICAL EXAMPLE")

marks = 85

if marks >= 90:
    grade = "A+"
elif marks >= 80:
    grade = "A"
elif marks >= 70:
    grade = "B"
elif marks >= 60:
    grade = "C"
else:
    grade = "Fail"

print("Marks:", marks)
print("Grade:", grade)

# Logical operator example
attendance = 80

if marks >= 40 and attendance >= 75:
    print("Result: PASS")
else:
    print("Result: FAIL")


print("\n========== PROGRAM COMPLETED ==========")

