# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LPH9cVDX50aOhCZK5QUg3lqzhx_CKosT
"""

# variables
name="Anmol Sharma" ##string
age=23
gender="male"
vehicle="bike"
universty="chandigarh universty"
semester="second semester"
company="Alpha IT Consultants"
marks=10.4
print(name)
print(age)
print(gender)
print(vehicle)
print(universty)
print(semester)
print(company)
print(type(name ))
print(type(age))
print(type(gender))
print(type(vehicle))
print(type(universty))
print(type(semester))
print(type(company))
print(type(marks))

## lIST,TUPLE,DICT
## LIST []
vegetables=["Carrot","Radish","Beetroot"," Turnip"]
print(vegetables)
print(type(vegetables))

##TUPLE ()
numbers=(10,20,30,40,50,60,70,80,90,100)
print(numbers)
print(type(numbers))

##DICT
person = {
    "name": "Anmol Sharma",
    "age": 23,
    "city": "Chandigarh"
}
print(person)
print(type(person))

text="Anmol Sharma"
print(text)

##length
print(len(text))

#Indexing
print(text[0])
print(text[1])
print(text[5])

#Navigate indexing
print(text[-1])
print(text[-2])

#Slicing
print(text[0:10])
print(text[11:])
print(text[:10])
print(text[5:15])

#Reserve string
print(text[::-1])

#Skip chracters
print(text[::2])

#String Methods
print(text.upper())

print(text.lower())

print(text.title())

print(text.capitalize())

print(text.swapcase())

print(text.replace("Sharma","Thakur"))

print(text.find("Sharma"))

print(text.count("n"))

print(text.startswith("Anmol"))

print(text.endswith("Sharma"))

print(text.split())

print(text.isalpha())

print(text.islower())

print(text.isupper())

print(text.center(40))

print(text.ljust(40))

print(text.rjust(40))

print(text.strip())

#How to work on list

students=["Rahul","Neha","Aman"]

print(students)

print(len(students))

print(students[0])

print(students[-1])

print(students[0:2])

##Add elements ("methods in list")

students.append("riya")

print(students)

students.insert(1,"ansh")

print(students)

students.extend(["karan","simran"])

print(students)



##remove the elments fromn the list

students.remove("Neha")

print(students)

students.pop()

print(students)

students.pop(3)

print(students)


##Update the elements in the list

students[0]="Rohan"

print(students)



## sort

students.sort()

print(students)

students.reverse()

print(students)


## Copy elemnts in the list

new_students=students.copy()

print(new_students)


##Count

numbers=[10,20,30,40,10,10,]

print(numbers.count(10))

#Index

print(numbers.index(20))

print(numbers.index(40))

## Pythobn practice assignment  PART:A
## Question 1: create a string with your full name and print it.
#Solution#
name="Anmol Sharma "
print(name)

##Question 2:print the length of the string.
## solution
print(len(name))

##QUESTION 3:print the first and last chracter .
##solution:
print(name[0])
print(name[-1])


##Question 4: print the first 5 and last 5 chracters.
##Solution:
print(name[0:5])
print(name[-5:])

##Question 5 :Print every alternate chracter using slicing.
##Solution:
print(name[::2])

##Question 6: Reverse the string using slicing.
##Solution:
print(name[::-1])

##Question 7: Convert the string to UPPERCASE,lowercase,Titlecase and captalise .
##solution:
print(name.upper())

print(name.lower())

print(name.title())

print(name.capitalize())

##Question 8: Replace your first name with another name .
##Solution:
print(name.replace("Anmol","Anshul"))


##question 9:Find the position of a word using find():
##Solution:
print(name.find("Sharma"))


##Question 10:Count how many times the letter 'a' appears.
##solution:
print(name.count("a"))

##Question 11:Check whether the string starts with a given word.
##Solution:
print(name.startswith("Anmol"))

##Question 12:Check whether the string ends with a given word.
##Solution:
print(name.endswith("Sharma"))

##Question 13:Split a sentence into words using split().
##Solution:
print(name.split())

##Question 14: Display the string using center(),ljust() and rjust(),
## solution:
print(name.center(40))

print(name.ljust(40))

print(name.rjust(40))


##Question 15: Remove the extra spaces using strip ().
##solution:
print(name.strip())

##Part B: List
##Question 16: Create a lisgt of five fruits and print it.
##solution:
fruits=["Apple","Grapes","KIWI","Banana","Mango"]
print(fruits)

##Question 17: Print the first and last fruit.
##solution:
print(fruits[0])
print(fruits[-1])

##Question 18: Print thwe first three fruits.
## solution:
print(fruits[:3])

##Question 19: Add one fruit using append .
##solution:
fruits.append("Guava")

print(fruits)

##Question 20: insert one fruit at index 2 using insert().
##Solution:
fruits.insert(2,"Dragon fruit")
print(fruits)


##Question 21: Add three fruits using extend().
##Solution:
fruits.extend(["Pineapple","Watermelon","Orange"])
print(fruits)

##Question 22: Remove one fruit using remove().
##Solution:
fruits.remove("Dragon fruit")
print(fruits)


##Question 23: Delete the last fruit using pop().
##Solution:
fruits.pop()
print(fruits)

##Question 24: Replace the second fruit with 'orange'.
##Solution:
fruits[1]="Orange"
print(fruits)


##Question 25:Sort the list alphabetically.
##Solution:
fruits.sort()
print(fruits)

##Question 26: Reverse the list.
##Solution:
fruits.reverse()
print(fruits)

##Question 27: Create a copy of the list.
##Solution:
new_fruits=fruits.copy()
print(new_fruits)

##Question 28: Create numbers=[10,20,30,40,10,50,10]and find count(10)and index(40).
##solution:
numbers=[10,20,30,40,10,50,10]
print(numbers.count(10))
print(numbers.index(40))

##Question 29:Print every item of the list (if loop has been taught).
##Solution:
for item in fruits:
    print(item)

##Question 30: Create marks =[[90,85],[75,80],[88,91]] and print 90, 80 and 91 using indexing.
##Solution:
marks =[[90,85],[75,80],[88,91]]
print(marks[0])
print(marks[1])

##Tuple

colors=("Red","Blue","Green","Yellow")
print (colors)


print(len(colors))

print(colors[0])

print(colors[-1])

print(colors[1:3])

print(colors.count("Red"))

print(colors.index("Green"))


##Packing

student=("rahul",21,"Delhi")

print(student)


##Unpacking

name,age,city= student

print(name)

print(age)

print(city)


##Nested Tuple(tuple ke under tuple)


data=((1,2),(3,4),(5,6))

print(data)

print (data[2])

print(data[2][1])


##SETS(it is agroup of objects)

A={10,20,30,40}

B={30,40,50,60}

print(A)

print(B)

##ADD


A.add(70)

print(A)


##Update

A.remove(20)

print(A)

##Discard

A.discard(100)

print(A)

##POP

A.pop()

print(A)

#####

name =input("enter name:")
print("hello",name)

State =input("enter state:")
print("hello",State)


age =input("enter age:")
print("hello",age)

###Airthmetic operator
a=int(input("A:"))
b=int(input("B:"))
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

##Comparison operator

a=20
b=10
print(a>b)
print(a<b)
print(a==b)
print(a!=b)
print(a>=b)
print(a<=b)

##Assignment operator
X=10
X+=4
print(X)
X-=4
print(X)
X*=3
print(X)
X/=2
print(X)

##Logical Operators

print(True and False)
print(True or False)
print(not True)
print(not False)

## Membership Operator

fruits=["Apple","Mango"]
print("Apple" in fruits)
print("orange" not in fruits )

##Task (Smart calculator)
print ("------Smart Calculator------")
num1=float(input("Enter first number:"))
num2=float(input("Enter second  number:"))

print("1.Addition   2.Substraction  3.Multiplication 4.Division 5.Modulus 6.Exponent 7.Floor Division")
choice=int(input("Enter your choice(1-7):"))
if choice == 1:
    print("Answer=",num1+num2 )
elif choice == 2:
 print("Answer=",num1 - num2)
elif choice == 3:
 print("Answer=",num1 * num2)
elif choice == 4:
    if num2 == 0:
        print("cannot divide by zero")
    else:
        print("Answer=",num1 / num2)

elif choice == 5:
    if num2 == 0:
        print("Cannot  perform  modulous by zero ")
    else:
        print("Answer=",num1 % num2)
elif choice == 6:
 print("Answer=",num1 ** num2)
elif choice == 7:
    if num2 == 0:
        print("Cannot perform Floor Division by zero ")
    else:
        print("Answer=",num1 // num2)

else:
    print("Invalid choice")

## statements (if, elif/else)
##(if else statement)
age=int(input ("enter the age "))
if age<=20:
  print("not allowed")
else:
    print("allowed")

###(if else statement)

marks=int(input("enter the marks"))
if marks>=95:
  print("A")
elif marks>=67:
 print('B')
else:
  print("C")

###loops
##(for loop)

fruits = ["apple", "banana", "cherry"]

for fruit in fruits:
    print(fruit)

for i in range(1,5):
      print(i)

for x in "mango":
  print(x)

text="Mango"
for i in range(len(text)):
  print("index",i,"character",text[i])

### while loop


text="python"
i=0
while i<len(text):
  print("index",i,"char",text[i])
  i+=1

## Break loop
for i in range(10):
  if i==5:
    break
  print(i)

##Factorial (in statements)

n=int(input("enter the number"))
f=1
for i in range(1,n+1):
 f*=i
 print(f)

###ASSIGNMENT :CONDITIONAL STATEMENTS AND LOOPS:
##Question1 Positive or Negative.
num = int(input("Enter a number: "))

if num > 0:
    print("Positive")
elif num < 0:
    print("Negative")
else:
    print("Zero")

##Question2 Even or Odd .
num = int(input("Enter a number: "))

if num % 2 == 0:
    print("Even")
else:
    print("Odd")

##Question3 Largest of Two Numbers .
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

if a > b:
    print("Largest =", a)
else:
    print("Largest =", b)

##Question4 Largest of Three Numbers.
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

if a >= b and a >= c:
    print("Largest =", a)
elif b >= a and b >= c:
    print("Largest =", b)
else:
    print("Largest =", c)

##Question5 Pass or Fail.
 marks = int(input("Enter marks: "))

if marks >= 40:
    print("Pass")
else:
    print("Fail")

##Question 6 Grade Calculator using if-elif.
marks = int(input("Enter marks: "))

if marks >= 90:
    print("Grade A")
elif marks >= 80:
    print("Grade B")
elif marks >= 70:
    print("Grade C")
elif marks >= 60:
    print("Grade D")
elif marks >= 40:
    print("Grade E")
else:
    print("Fail")

##Question 7 Voting Eligibility.
age = int(input("Enter age: "))

if age >= 18:
    print("Eligible to Vote")
else:
    print("Not Eligible")

##Question 8 Login System.
username = input("Enter username: ")
password = input("Enter password: ")

if username == "anmol" and password == "1234":
    print("Login Successful")
else:
    print("Invalid Username or Password")

##Question9 Leap Year Checker.
year = int(input("Enter year: "))

if (year % 400 == 0) or (year % 4 == 0 and year % 100 != 0):
    print("Leap Year")
else:
    print("Not a Leap Year")

##Question10 Calculator using if-elif.
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
op = input("Enter operator (+,-,*,/): ")

if op == "+":
    print("Result =", a + b)
elif op == "-":
    print("Result =", a - b)
elif op == "*":
    print("Result =", a * b)
elif op == "/":
    if b != 0:
        print("Result =", a / b)
    else:
        print("Division by zero is not allowed")
else:
    print("Invalid Operator")

##loops Question

##Question 11 Print 1 to 20.
for i in range(1, 21):
    print(i)

##Question12 Print Even Numbers.
for i in range(2, 21, 2):
    print(i)

## Question13 Print Odd Numbers.
for i in range(1, 21, 2):
    print(i)

##Question14 Multiplication Table.
num = int(input("Enter a number: "))

for i in range(1, 11):
    print(num, "x", i, "=", num * i)

##Question15 Sum of First N Numbers.
n = int(input("Enter a number: "))
sum = 0

for i in range(1, n + 1):
    sum += i

print("Sum =", sum)

###Question16 Factorial.
n = int(input("Enter a number: "))

fact = 1

for i in range(1, n + 1):
    fact *= i

print("Factorial =", fact)

##Question17 Reverse Counting (10 to 1).
for i in range(10, 0, -1):
    print(i)

##Question18 Print Characters of a String.
text = input("Enter a string: ")

for char in text:
    print(char)

##Question19 Print List Elements.
numbers = [10, 20, 30, 40, 50]

for item in numbers:
    print(item)

##Question20 Count Vowels.
text = input("Enter a string: ")

count = 0

for ch in text.lower():
    if ch in "aeiou":
        count += 1

print("Number of vowels =", count)

##Part C – break & continue.
##Question 21 Stop printing when number becomes 6 using break.
for i in range(1, 11):
    if i == 6:
        break
    print(i)

##Question22 Skip number 5 using continue.
for i in range(1, 11):
    if i == 5:
        continue
    print(i)

##FUNCTION
def fahrenheit_to_celsius(fahrenheit):
  return (fahrenheit - 32) * 5 / 9

print(fahrenheit_to_celsius(77))
print(fahrenheit_to_celsius(95))
print(fahrenheit_to_celsius(50))

##Function with parameter
def greet(name):
    print('Hello',name)
greet('Rahul')

## multi parameter
def add(a,b):
 print(a+b)
add(10,20)

##Return statement
def square(n):
 return n*n
print(square(11))

###Default Argument
def greet(name="Guest"):
 print("Hello",name)
greet()
greet("Rahul")

##Keyword Argument
def student(name,age):
 print(name,age)
student(age=20,name='Rahul')

### Python Programming Assignment (5-Day Practice)

#Reverse a String
text = input("Enter a string: ")
print("Reversed String:", text[::-1])

#Count Vowels
text = input("\nEnter another string: ")
count = 0
for ch in text.lower():
    if ch in "aeiou":
        count += 1
print("Number of vowels:", count)

#String Methods
text = input("\nEnter a string: ")
print("Upper:", text.upper())
print("Lower:", text.lower())
print("Title:", text.title())
print("Length:", len(text))

#List Operations
numbers = [10, 20, 30, 40]
numbers.append(50)
numbers.insert(2, 25)
numbers.remove(20)
print("\nList Operations:", numbers)

#Largest and Smallest in a List
numbers = [12, 45, 7, 89, 23]
print("Largest:", max(numbers))
print("Smallest:", min(numbers))

###Tuple set and Dictionary

# Tuple Indexing
fruits = ("Apple", "Banana", "Mango", "Orange")
print("\nFirst Fruit:", fruits[0])
print("Last Fruit:", fruits[-1])

#Set Union & Intersection
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}
print("Union:", set1 | set2)
print("Intersection:", set1 & set2)

#Student Dictionary
student = {
    "Name": "Rahul",
    "Age": 20,
    "Marks": 85
}
print(student)

#Update & Delete Values
student["Marks"] = 90
del student["Age"]
print("Updated Dictionary:", student)

#Print Keys and Values
print("Keys:")
for key in student.keys():
    print(key)

print("Values:")
for value in student.values():
    print(value)

##Input, Operators & Conditions

#Calculator
a = float(input("\nEnter first number: "))
b = float(input("Enter second number: "))
op = input("Enter operator (+,-,*,/): ")

if op == "+":
    print("Result:", a + b)
elif op == "-":
    print("Result:", a - b)
elif op == "*":
    print("Result:", a * b)
elif op == "/":
    if b != 0:
        print("Result:", a / b)
    else:
        print("Division by zero not allowed.")
else:
    print("Invalid Operator")

#Grade Calculator
marks = float(input("\nEnter Marks: "))

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 60:
    print("Grade: C")
elif marks >= 40:
    print("Grade: D")
else:
    print("Grade: F")

#Voting Eligibility
age = int(input("\nEnter Age: "))
if age >= 18:
    print("Eligible to Vote")
else:
    print("Not Eligible")

# Largest of Three Numbers
a = int(input("\nEnter First Number: "))
b = int(input("Enter Second Number: "))
c = int(input("Enter Third Number: "))

largest = max(a, b, c)
print("Largest Number:", largest)

#Electricity Bill
units = int(input("\nEnter Units Consumed: "))

if units <= 100:
    bill = units * 5
elif units <= 200:
    bill = 100 * 5 + (units - 100) * 7
else:
    bill = 100 * 5 + 100 * 7 + (units - 200) * 10

print("Electricity Bill =", bill)

##Loops

 #Multiplication Table
num = int(input("\nEnter Number: "))
for i in range(1, 11):
    print(num, "x", i, "=", num * i)

#Factorial
num = int(input("\nEnter Number: "))
fact = 1
for i in range(1, num + 1):
    fact *= i
print("Factorial:", fact)

#Sum of N Numbers
n = int(input("\nEnter N: "))
total = 0
for i in range(1, n + 1):
    total += i
print("Sum:", total)

#Fibonacci Series
n = int(input("\nEnter Number of Terms: "))
a, b = 0, 1

print("Fibonacci Series:")
for i in range(n):
    print(a, end=" ")
    a, b = b, a + b
print()

#Prime Number Check
num = int(input("\nEnter Number: "))

if num > 1:
    prime = True
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            prime = False
            break

    if prime:
        print("Prime Number")
    else:
        print("Not a Prime Number")
else:
    print("Not a Prime Number")

###Functions

#Even/Odd Function
def even_odd(n):
    if n % 2 == 0:
        return "Even"
    return "Odd"

print("\nEven/Odd:", even_odd(10))

# Area of Circle
def area_circle(radius):
    return 3.14 * radius * radius

print("Area:", area_circle(5))

#Average Marks
def average(m1, m2, m3):
    return (m1 + m2 + m3) / 3

print("Average:", average(80, 75, 90))

#Student Result System
def result(marks):
    avg = sum(marks) / len(marks)
    if avg >= 40:
        return "Pass"
    return "Fail"

marks = [65, 70, 80,90]
print("Student Result:", result(marks))

#Calculator using Functions
def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b != 0:
        return a / b
    return "Division by zero not allowed"

print("Addition:", add(10, 5))
print("Subtraction:", subtract(10, 5))
print("Multiplication:", multiply(10, 5))
print("Division:", divide(10, 5))

###BONUS PROJECTS
  #Number Guessing Game
secret = 7
guess = int(input("\nGuess a Number (1-10): "))

if guess == secret:
    print("Congratulations! Correct Guess.")
else:
    print("Wrong Guess. Secret Number was", secret)

#Password Checker
password = input("\nEnter Password: ")

if len(password) >= 8:
    print("Strong Password")
else:
    print("Weak Password")

#Simple ATM Menu
balance = 500000

while True:
    print("== ATM MENU ==")
    print("1. Check Balance")
    print("2. Deposit")
    print("3. Withdraw")
    print("4. Exit")

    choice = input("Enter Choice: ")

    if choice == "1":
        print("Balance:", balance)

    elif choice == "2":
        amount = float(input("Enter Deposit Amount: "))
        balance += amount
        print("Updated Balance:", balance)

    elif choice == "3":
        amount = float(input("Enter Withdrawal Amount: "))
        if amount <= balance:
            balance -= amount
            print("Updated Balance:", balance)
        else:
            print("Insufficient Balance")

    elif choice == "4":
        print("Thank You for Using ATM")
        break

    else:
        print("Invalid Choice")

