# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ONmI604PDUN8NS9XMVJ9UzGCj6wZbwHF

## Command-Line Smart Calculator

As explained earlier, GUI applications like the Tkinter calculator cannot be run directly within Google Colab due to the lack of a graphical display environment.

However, we can create a functional 'smart calculator' that operates via the command line (or directly within a code cell). This version will allow you to input mathematical expressions as strings and get the calculated result. It will support standard arithmetic operations and some common scientific functions.
"""

import math

def smart_calculate(expression):
    """
    Evaluates a mathematical expression given as a string, supporting
    basic arithmetic and common scientific functions from the math module.

    Args:
        expression (str): The mathematical expression to evaluate.

    Returns:
        str: The result of the expression or an error message.
    """
    # Replace common calculator symbols with Python equivalents
    expression = expression.replace('×', '*').replace('÷', '/').replace('−', '-')

    # Define a safe environment for eval to prevent arbitrary code execution
    # Allow a subset of math module functions
    allowed_functions = {
        'sin': math.sin,
        'cos': math.cos,
        'tan': math.tan,
        'sqrt': math.sqrt,
        'log': math.log,
        'log10': math.log10,
        'exp': math.exp,
        'radians': math.radians,
        'degrees': math.degrees,
        'pi': math.pi,
        'e': math.e
    }

    # Use a limited global and local dictionary for eval
    safe_dict = {'__builtins__': None}
    safe_dict.update(allowed_functions)

    try:
        # Evaluate the expression
        result = eval(expression, safe_dict)

        # Format integer results as integers
        if isinstance(result, float) and result.is_integer():
            return str(int(result))
        return str(result)
    except ZeroDivisionError:
        return "Error: Cannot divide by zero"
    except SyntaxError:
        return "Error: Invalid expression syntax"
    except TypeError:
        return "Error: Invalid arguments for a function"
    except NameError as e:
        # Catch cases where unauthorized functions/variables are used
        return f"Error: Unauthorized function or variable used ({e})"
    except Exception as e:
        return f"Error: {e}"

"""### Calculator Usage Examples"""

# Basic arithmetic
print(f"5 + 3 = {smart_calculate('5 + 3')}")
print(f"10 × 2 = {smart_calculate('10 * 2')}")
print(f"15 ÷ 3 = {smart_calculate('15 / 3')}")
print(f"7 − 4 = {smart_calculate('7 - 4')}")
print(f"(2 + 3) * 4 = {smart_calculate('(2 + 3) * 4')}")
print(f"2 ** 3 = {smart_calculate('2 ** 3')}")

# Scientific functions
print(f"sin(90 degrees) = {smart_calculate('sin(radians(90))')}")
print(f"sqrt(25) = {smart_calculate('sqrt(25)')}")
print(f"log10(100) = {smart_calculate('log10(100)')}")
print(f"pi * 2 = {smart_calculate('pi * 2')}")
print(f"e = {smart_calculate('e')}")

# Error cases
print(f"10 / 0 = {smart_calculate('10 / 0')}")
print(f"5 + = {smart_calculate('5 + ')}")
print(f"custom_func(5) = {smart_calculate('custom_func(5)')}")